### ISSUE TITLE
unable to hit api

### ISSUE THREAD

**Issue by TheReprator** [DroidKaigi/conference-app-2021#232] opened 2021-03-02 09:11 UTC
When i launch the app, it's just showing empty screen on click of any icon, no data or loading is there, on android phones.

![device-2021-03-02-144117](https://user-images.githubusercontent.com/10286587/109625477-63ba5000-7b65-11eb-9954-7b40954690f0.png)

**Comment by TheReprator** [comment] 2021-03-02 09:12
Please let me know, how to fix this

**Comment by takahirom** [comment] 2021-03-02 09:15
Thank you for reporting.
Probably caused by the following problem, but we do not currently know how to deal with it.
This problem may be improved by restarting the application.
https://github.com/DroidKaigi/conference-app-2021/issues/93

**Comment by takahirom** [comment] 2021-03-02 09:19
If restarting the app doesn't work, I would appreciate it if you could provide the logcat log for investigation. 🙏

**Comment by takahirom** [comment] 2021-03-02 13:19
I will close this issue once, so please let me know if there is anything else at any time.

**Closed** 2021-03-02 13:21 UTC
